### ISSUE TITLE
Ebook

### ISSUE THREAD

**Issue by balarajuyogesh** [Hemant-Jain-Author/Data-Structures-and-Algorithms-using-JavaScript-ES6#1]
I am Yogesh from India. I am looking forward to purchase this ebook. I request you to provide me an appropriate link

**Comment by Hemant-Jain-Author** [comment]
We will make indian edition available at affordable cost. Not have any plan to release kindle education.

**Comment by Hemant-Jain-Author** [comment]
ebooks are copied so not publishing ebooks.
